const nationaliteiten = [
  { nationaliteit: "Afgaanse" },
  { nationaliteit: "Albanese" },
  { nationaliteit: "Albanese" },
  { nationaliteit: "Algerijse" },
  { nationaliteit: "Amerikaans burger" },
  { nationaliteit: "Amerikaans onderdaan" },
  { nationaliteit: "Andorrese" },
  { nationaliteit: "Angolese" },
  { nationaliteit: "Antigua" },
  { nationaliteit: "Argentijnse" },
  { nationaliteit: "Armenië, burger van" },
  { nationaliteit: "Australische" },
  { nationaliteit: "Azerbeidzjan, burger van" },
  { nationaliteit: "Bahamaanse" },
  { nationaliteit: "Bahreinse" },
  { nationaliteit: "Bangladesh, burger van" },
  { nationaliteit: "Barbadaanse" },
  { nationaliteit: "Belarus, burger van" },
  { nationaliteit: "Belgische" },
  { nationaliteit: "Belizaanse" },
  { nationaliteit: "Beninse" },
  { nationaliteit: "Bhutaanse" },
  { nationaliteit: "Boliviaanse" },
  { nationaliteit: "Bosnië-Herzegovina, burger" },
  { nationaliteit: "Botswaanse" },
  { nationaliteit: "Braziliaanse" },
  { nationaliteit: "British National (overseas)" },
  { nationaliteit: "Brits burger" },
  { nationaliteit: "Brits onderdaan" },
  { nationaliteit: "Brits overzees burger" },
  { nationaliteit: "Britse afhankelijke gebieden, burger van" },
  { nationaliteit: "Bruneise" },
  { nationaliteit: "Bulgaarse" },
  { nationaliteit: "Burkinese" },
  { nationaliteit: "Burundische" },
  { nationaliteit: "Cambodjaanse" },
  { nationaliteit: "Canadese" },
  { nationaliteit: "Centraal-Afrikaanse" },
  { nationaliteit: "Chileense" },
  { nationaliteit: "Chinese" },
  { nationaliteit: "Colombiaanse" },
  { nationaliteit: "Comorese" },
  { nationaliteit: "Costaricaanse" },
  { nationaliteit: "Cubaanse" },
  { nationaliteit: "Cyprische" },
  { nationaliteit: "Deense" },
  { nationaliteit: "Djiboutiaanse" },
  { nationaliteit: "Dominica, burger van" },
  { nationaliteit: "Dominicaanse Rupubliek, burger van" },
  { nationaliteit: "Duitsland, burger van Bondsrepubliek" },
  { nationaliteit: "Ecuadoraanse" },
  { nationaliteit: "Egyptische" },
  { nationaliteit: "Equatoriaal-Guinese" },
  { nationaliteit: "Eritrese" },
  { nationaliteit: "Estland, burger van" },
  { nationaliteit: "Etiopische" },
  { nationaliteit: "Fijische" },
  { nationaliteit: "Filipijnse" },
  { nationaliteit: "Finse" },
  { nationaliteit: "Franse" },
  { nationaliteit: "Gabonese" },
  { nationaliteit: "Gambiaanse" },
  { nationaliteit: "Georgië, burger van" },
  { nationaliteit: "Ghanese" },
  { nationaliteit: "Grenadaanse" },
  { nationaliteit: "Griekse" },
  { nationaliteit: "Guatemalteekse" },
  { nationaliteit: "Guinee-Bissause" },
  { nationaliteit: "Guinese" },
  { nationaliteit: "Guyaanse" },
  { nationaliteit: "Haïtiaanse" },
  { nationaliteit: "Hondurese" },
  { nationaliteit: "Hongaarse" },
  { nationaliteit: "Ierse" },
  { nationaliteit: "Ijslandse" },
  { nationaliteit: "Ijslandse" },
  { nationaliteit: "India, burger van" },
  { nationaliteit: "Indonesische" },
  { nationaliteit: "Iraakse" },
  { nationaliteit: "Iraanse" },
  { nationaliteit: "Israëlische" },
  { nationaliteit: "Italiaanse" },
  { nationaliteit: "Ivoriaanse" },
  { nationaliteit: "Jamaicaanse" },
  { nationaliteit: "Japanse" },
  { nationaliteit: "Jemenitische" },
  { nationaliteit: "Jordaanse" },
  { nationaliteit: "Kaapverdische" },
  { nationaliteit: "Kameroense" },
  { nationaliteit: "Kazachstan, burger van" },
  { nationaliteit: "Keniaanse" },
  { nationaliteit: "Kiribatische" },
  { nationaliteit: "Koeweitse" },
  { nationaliteit: "Kongolese" },
  { nationaliteit: "Kosovo, burger van" },
  { nationaliteit: "Kroatië, burger van" },
  { nationaliteit: "Kyrgyzstan, burger van" },
  { nationaliteit: "Laotiaanse" },
  { nationaliteit: "Lesothaanse" },
  { nationaliteit: "Letse" },
  { nationaliteit: "Libanese" },
  { nationaliteit: "Liberiaanse" },
  { nationaliteit: "Libische" },
  { nationaliteit: "Liechtensteinse" },
  { nationaliteit: "Litouwse" },
  { nationaliteit: "Luxemburgse" },
  { nationaliteit: "Macedonische" },
  { nationaliteit: "Malagassische" },
  { nationaliteit: "Malawische" },
  { nationaliteit: "Maldivische" },
  { nationaliteit: "Maleisische" },
  { nationaliteit: "Malinese" },
  { nationaliteit: "Maltese" },
  { nationaliteit: "Marokkaanse" },
  { nationaliteit: "Marshalleilandse" },
  { nationaliteit: "Mauritanië, burger van" },
  { nationaliteit: "Mauritius, burger van" },
  { nationaliteit: "Mexicaanse" },
  { nationaliteit: "Moldavië, burger van" },
  { nationaliteit: "Monegaskische" },
  { nationaliteit: "Mongolische" },
  { nationaliteit: "Montenegro, burger van" },
  { nationaliteit: "Mozambiquaanse" },
  { nationaliteit: "Myanmarese" },
  { nationaliteit: "Namibische" },
  { nationaliteit: "Nauruaanse" },
  { nationaliteit: "Nederlandse" },
  { nationaliteit: "Nepalese" },
  { nationaliteit: "Nicaraguaanse" },
  { nationaliteit: "Nieuw-Zeelandse" },
  { nationaliteit: "Niger, burger van" },
  { nationaliteit: "Nigeria, burger van" },
  { nationaliteit: "Noord-Koreaanse" },
  { nationaliteit: "Noorse" },
  { nationaliteit: "Oekraine, burger van" },
  { nationaliteit: "Oezbekistan, burger van" },
  { nationaliteit: "Omanitische" },
  { nationaliteit: "Onbekend" },
  { nationaliteit: "Oostenrijkse" },
  { nationaliteit: "Oost-Timorese" },
  { nationaliteit: "Pakistaanse" },
  { nationaliteit: "Panamese" },
  { nationaliteit: "Papoea-Nieuw-Guinea, burger van" },
  { nationaliteit: "Paraguayaanse" },
  { nationaliteit: "Peruaanse" },
  { nationaliteit: "Poolse" },
  { nationaliteit: "Portugese" },
  { nationaliteit: "Qatarese" },
  { nationaliteit: "Roemeense" },
  { nationaliteit: "Rusland, burger van" },
  { nationaliteit: "Rwandese" },
  { nationaliteit: "Saint Kitts en Nevis, burger van" },
  { nationaliteit: "Saint Luciaanse" },
  { nationaliteit: "Saint Vincent en de Grenadines, burger van" },
  { nationaliteit: "Salomonseilandse" },
  { nationaliteit: "Salvadoraanse" },
  { nationaliteit: "Samoaanse" },
  { nationaliteit: "Sanmarinese" },
  { nationaliteit: "Sao Tomé en Principe, burger van" },
  { nationaliteit: "Saoedi-Arabische" },
  { nationaliteit: "Senegalese" },
  { nationaliteit: "Servië, burger van" },
  { nationaliteit: "Seychelse" },
  { nationaliteit: "Sierraleoonse" },
  { nationaliteit: "Singaporaanse" },
  { nationaliteit: "Slovenië, burger van" },
  { nationaliteit: "Slowaakse" },
  { nationaliteit: "Soedanese" },
  { nationaliteit: "Somalische" },
  { nationaliteit: "Spaanse" },
  { nationaliteit: "Srilankaanse" },
  { nationaliteit: "Staatloos" },
  { nationaliteit: "Surinaamse" },
  { nationaliteit: "Swazische" },
  { nationaliteit: "Syrische" },
  { nationaliteit: "Tadzjiekse" },
  { nationaliteit: "Taiwanese" },
  { nationaliteit: "Tanzaniaase" },
  { nationaliteit: "Thaise" },
  { nationaliteit: "Togolese" },
  { nationaliteit: "Tongaanse" },
  { nationaliteit: "Trinidad en Tobago, burger van" },
  { nationaliteit: "Tsjadische" },
  { nationaliteit: "Tsjechische" },
  { nationaliteit: "Tunesische" },
  { nationaliteit: "Turkmeense" },
  { nationaliteit: "Turkse" },
  { nationaliteit: "Tuvaluaanse" },
  { nationaliteit: "Ugandese" },
  { nationaliteit: "Uruguayaanse" },
  { nationaliteit: "Vanuatuse" },
  { nationaliteit: "Vaticaanse" },
  { nationaliteit: "Venezolaanse" },
  { nationaliteit: "Verenigde Arabische Emiraten, burger van de" },
  { nationaliteit: "Viëtnamese" },
  { nationaliteit: "Zaïrese" },
  { nationaliteit: "Zambiaanse" },
  { nationaliteit: "Zimbabwaanse" },
  { nationaliteit: "Zuid-Afrikaanse" },
  { nationaliteit: "Zuid-Koreaanse" },
  { nationaliteit: "Zweedse" },
  { nationaliteit: "Zwitserse" },
];

export default nationaliteiten;
